name: docker-backfill
services:
  docker-backfill:
    build:
      context: ..services/EOD_Data
      dockerfile: Dockerfile
    env_file:
      - ..services/EOD_Data/local_backfill.env
      - ..services/EOD_Data/api_key.env
    restart: no
